### ISSUE TITLE
Roadmap (Missing Features on Website)

### ISSUE THREAD

**Issue by cookiengineer** [polyfillr/polyfillr.github.io#1]
The website needs these views/sections in order to have an understandable state for newcomers to the Polyfillr framework:

**Boilerplate Section**

- [ ] `boilerplate/index.html` to show off the Polyfillr Boilerplate Features and a Live Demo.
- [ ] Automatically generated download (zip-file) for `polyfillr-boilerplate.zip`.

**/demo section**

- [ ] `demo/index.html`
- [ ] `demo/console.html`
- [ ] `demo/ecmascript.html`
- [ ] `demo/components.html`

**/api section**

- [ ] `api/index.html`
- [ ] Console API
- [ ] ECMAScript API (really necessary!?)
- [ ] Components API
